### ISSUE TITLE
0.1.0 release tasks checklist

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Blazor#296]
- [x] Blog post - @danroth27 
- [x] Verification: installation steps, follow tutorial in blog post - @kichalla 
- [x] Add survey link - @danroth27 supply URL, @SteveSandersonMS add code
- [x] Add release to GitHub - @danroth27 
- [x] Push signed packages to MyGet (version `0.1.0`) - @SteveSandersonMS
- [x] Upload VSIX to VS Gallery - Upload from corpnet and assign Microsoft as the publish, add multiple owners - @danroth27
- [x] Publish FlightFinder sample to GitHub - @SteveSandersonMS
- [x] Check third-party notices, licenses, etc. - @danroth27 
- [x] Repo README updates - @danroth27 

In blog post, document known issues:

 * Currently you can't use `data-*` attributes with C#-expression values (e.g., `<div data-something=@value />` does not compile). Workaround: write `data_*` instead (e.g., `<div data_something=@value />`), and we'll render it as `data-*` in the DOM. Tracked as #297 
 * If you create a project with a space or hyphen in the project name, the result app has build errors. Workaround: don't put spaces or hyphens in the project name. Tracked as #291

**Comment by YandyZaldivar** [comment]
Will this release work in Visual Studio 15.6.0 or I need to use Visual Studio preview?

**Comment by SteveSandersonMS** [comment]
@YandyZaldivar It requires 15.7 Preview 1 because the component intellisense uses new editor APIs added in that version.

**Comment by felipemullen** [comment]
Looking forward to trying this out. Awesome work so far 👍

**Comment by vibeeshan025** [comment]
👍

**Comment by aaronwJordan** [comment]
I am so excited for this project! Keep up the great work!

**Comment by juho-hanhimaki** [comment]
👍

**Comment by vertonghenb** [comment]
First of all keep up the amazing work, we're looking forward to the "post javascript era".
Some questions though:
- Will there be another podcast on the ASP.NET Community Standup (live.asp.net)?
- Something minor but is Visual Studio for Mac supported in this 0.1.0 release?

**Comment by danroth27** [comment]
@vertonghenb 

> Will there be another podcast on the ASP.NET Community Standup (live.asp.net)?

Yup, although it will probably be a few weeks out.

> Something minor but is Visual Studio for Mac supported in this 0.1.0 release?

Not for 0.1.0, but we are working on it. First thing is to get sufficient Razor support in VS for Mac.

**Comment by Eilon** [comment]
Added @kichalla for this item:
*  Verification: installation steps, follow tutorial in blog post

cc @mkArtakMSFT

**Comment by mihail-shishkov** [comment]
This is so good, I still can't believe it's true.

**Comment by SteveSandersonMS** [comment]
The release is out :)
